#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    s = input()
    l=list(set(list(s)))
    k={}
    for i in l:
        if s.count(i) not in k:
            k[s.count(i)]=[i]
        else:
            p=0
            for j in k[s.count(i)]:
                if j>i:
                    k[s.count(i)].insert(p,i)
                    break
                p+=1
            else:
                k[s.count(i)].append(i) 
    p=list(k.keys())
    p.sort(reverse=True)
    f=[]
    for i in p:
        for j in k[i]:
            f.append([j,i])
            if len(f)==3:
                break
        if len(f)==3:
                break
    for i in f:
        print(i[0],i[1])
        
    
