#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'counterGame' function below.
#
# The function is expected to return a STRING.
# The function accepts LONG_INTEGER n as parameter.
#

def counterGame(n):
    c=0
    while n!=1:
        c+=1
        k=n
        p=0
        while k!=1:
            p+=1
            k//=2
        k=math.sqrt(n)
        if n==2**p:
            n//=2
        else:
            k=math.sqrt(n)
            n=n-(2**p)
    if c%2==1:
        return "Louise"
    return "Richard"
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = counterGame(n)

        fptr.write(result + '\n')

    fptr.close()
999
