#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gridChallenge' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING_ARRAY grid as parameter.
#

def gridChallenge(grid):
    k=[]
    #print(grid)
    for i in range(len(grid)):
        k.append([])
        for j in grid[i]:
            k[-1].append(j)
        k[-1].sort()
    #print(k)
    for i in range(len(k)-1):
        for j in range(len(k[i])):
            if k[i][j]>k[i+1][j]:
                #print(k[i][j],k[i+1][j])
                return "NO"
    return "YES"
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        grid = []

        for _ in range(n):
            grid_item = input()
            grid.append(grid_item)

        result = gridChallenge(grid)

        fptr.write(result + '\n')

    fptr.close()
